SET storage_engine = INNODB;

DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Thread;
DROP TABLE IF EXISTS User;

CREATE TABLE User(
U_ID INT NOT NULL AUTO_INCREMENT,
Screen_Name CHAR( 32 ) NOT NULL ,
Join_Date DATE NOT NULL ,
Password CHAR(64) NOT NULL ,
PRIMARY KEY ( U_ID )
);
CREATE TABLE Post(
P_Number INT NOT NULL AUTO_INCREMENT,
T_ID INT NOT NULL ,
U_ID INT NOT NULL ,
Post_Time DATETIME NOT NULL ,
Last_Edit_Time DATETIME ,
Content TEXT NOT NULL ,
PRIMARY KEY ( P_Number, T_ID )
);
CREATE TABLE Thread(
T_ID INT NOT NULL AUTO_INCREMENT,
U_ID INT NOT NULL ,
Creation_Time DATETIME NOT NULL ,
Title CHAR( 40 ) NOT NULL ,
PRIMARY KEY ( T_ID )
);
#(Instantiate foreign key pointers)
ALTER TABLE Thread ADD FOREIGN KEY ( U_ID )REFERENCES User( U_ID );
ALTER TABLE Post ADD FOREIGN KEY ( T_ID ) REFERENCES Thread( T_ID );
ALTER TABLE Post ADD FOREIGN KEY ( U_ID ) REFERENCES User( U_ID );
#(Create the admin user with password "Password")
INSERT INTO User
VALUES ( null, 'Admin', '2012-06-10', '4b939e3aa91af9ceee4b64ab52ea517c0435254d69b2a32f1189a5b9a8a83ba5') ; 
INSERT INTO User
VALUES ( null, 'Username', '2012-06-10', '') ; #don't allow "username to be valid"